<Project Sdk="Microsoft.NET.Sdk">

    <Import Project="..\..\common.props" />

    <PropertyGroup>
        <TargetFramework>net6.0</TargetFramework>
        <GenerateEmbeddedFilesManifest>true</GenerateEmbeddedFilesManifest>
        <RootNamespace>Acme.PhamacyManagement</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Volo.Abp.VirtualFileSystem" Version="6.0.0" />
    </ItemGroup>

    <ItemGroup>
      <None Remove="..\..\Acme.PhamacyManagement.abpmdl.json" />
      <EmbeddedResource Include="..\..\Acme.PhamacyManagement.abpmdl.json" />
    </ItemGroup>

</Project>
