<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\..\common.props" />

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <RootNamespace>Acme.PhamacyManagement</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.2.0" />
    <ProjectReference Include="..\Acme.PhamacyManagement.EntityFrameworkCore.Tests\Acme.PhamacyManagement.EntityFrameworkCore.Tests.csproj" />
  </ItemGroup>

</Project>
